{% set name = "napari-micromanager" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6cecefcbc33dca8de01cb78943e0623942afe02e04426d968db288037d05133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - fonticon-materialdesignicons6
    - napari >=0.4.13
    - pymmcore-plus >=0.1.5
    - python >=3.8
    - superqt >=0.3.1
    - tifffile
    - useq-schema >=0.1.0
    - fonticon-materialdesignicons6

test:
  imports:
    - micromanager_gui
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/napari-micromanager
  summary: GUI interface between napari and micromanager
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tlambert03
