{% set name = "napari-micromanager" %}
{% set version = "0.0.1rc7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-micromanager-{{ version }}.tar.gz
  sha256: 3bf7bfddc2863d5bfe7342825d053e54b1d652f3c87305709c886fab6346e57a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui >=0.3.0
    - napari
    - pymmcore-plus >=0.1.5
    - python >=3.8
    - scikit-image
    - tqdm
    - useq-schema >=0.1.0

test:
  imports:
    - micromanager_gui
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/napari-micromanager
  summary: GUI interface between napari and micromanager
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - tlambert03
