{% set name = "napari-micromanager" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6cecefcbc33dca8de01cb78943e0623942afe02e04426d968db288037d05133

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - napari-micromanager = napari_micromanager.__main__:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - fonticon-materialdesignicons6
    - napari >=0.4.13
    - numpy
    - pymmcore-plus >=0.8.0
    - pymmcore-widgets >=0.4.2
    - python >=3.8
    - qtpy
    - superqt >=0.5.1
    - tifffile
    - useq-schema >=0.4.1
    - zarr

test:
  imports:
    - micromanager_gui
  commands:
    - pip list
    - pip check
    - napari-micromanager
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-micromanager
  summary: GUI interface between napari and micromanager
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/tlambert03/napari-micromanager

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tlambert03
